site_name: AGL Application Framework
theme: readthedocs
docs_dir: docs
pages:
  - 'Introduction' : 'index.md'
  - 'The afm daemons' : '1-afm-daemons.md'
  - 'Widgets' :
      - '' : '2-widgets.md'
      - 'Overview of widgets' : '2.1-widgets.md'
      - 'The configuration file' : '2.2-config.xml.md'
  - 'The permissions' : '3-permissions.md'
  - 'Quick tutorial' : '4-quick-tutorial.md'
  - 'History' : 'a-history.md'
  - 'Document revisions' : 'REVISIONS.md'
