site_name: AGL Application Framework
theme: readthedocs
docs_dir: docs
pages:
  - 'Overview' : 'index.md'
  - 'Quick tutorial' : 'quick-tutorial.md'
  - 'The frameworks' :
      - 'The application framework': 'application-framework.md'
      - 'The security framework': 'security-framework.md'
  - 'The afm daemons' : 'afm-daemons.md'
  - 'Widgets of the framework' :
      - 'Overview of widgets': 'widgets.md'
      - 'The configuration file': 'config.xml.md'
